### ISSUE TITLE
cannot get docker build of catanie to connect to catamel running locally

### ISSUE THREAD

**Issue by LAShemilt** [SciCatProject/catanie#738]
## Issue Name
Docker Build does not work locally

### Summary

I am trying to update my scicat service locally so I can test some features before going to production. I was using the dockerhub image of dacat/catanie with the following docker compose file to connect everything locally and this works well:
```
version: "3.8"
services:
  reverse-proxy:
    image: traefik:latest
    command: --api.insecure=true --providers.docker=true --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongodb:
    image: bitnami/mongodb:4.0
    volumes:
      #- "/mongodb:/bitnami"
      - "mongodb_data:/bitnami"
    ports:
      - "27017:27017"
  openldap:
    image: osixia/openldap:latest
    hostname: openldap
    volumes:
      - ./config/ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: --copy-service --loglevel debug
    environment:
      LDAP_TLS_VERIFY_CLIENT: never
      LDAP_DOMAIN: rfi.ac.uk
      LDAP_TLS: "false"
    ports:
      - "389:389"
  catamel:
    image: dacat/catamel:latest
    depends_on:
      - mongodb
      - openldap
    volumes:
      - ./config/catamel/config.local.js:/home/node/app/server/config.local.js
      - ./config/catamel/providers.json:/home/node/app/server/providers.json
    labels:
      - "traefik.http.routers.catamel.rule=PathPrefix(`/api`, `/auth`, `/explorer`)"
      - "traefik.http.routers.catamel.entrypoints=web"
  catanie:
   image: dacat/latest
    depends_on:
      - catamel
    labels:
      - "traefik.http.routers.catanie.rule=PathPrefix(`/`)"
      - "traefik.http.routers.catanie.entrypoints=web"
volumes:
  mongodb_data:
    driver: local
```
However I know want to change the environment.ts file to add some features to the GUI that are not in dacat/catamie docker file. To do this I am editing the environment.rfi.dev.ts file and building an image from CI/RFI/Dockerfile.dev:
```
  catanie:
    build:
      context: ../catanie
      dockerfile: CI/RFI/Dockerfile.dev
    image: catanie-test
    depends_on:
      - catamel
    labels:
      - "traefik.http.routers.catanie.rule=PathPrefix(`/`)"
      - "traefik.http.routers.catanie.entrypoints=web"
```
When doing this I cannot got catanie to talk to catamel. I have edited the `lbBaseURL` argument in the environment.ts file to  , `http://catamel:3000`  and  `http://localhost:3000` but I cannot seem to get catamel talking to catanie at all. The catamel logs show no requests have been made to it when I try to login and it does not display the public datasets on the login screen.  The Dockerfile that I am using to build catanie is fairly old so this could be the problem. 

Which Dockerfile and environment.ts file are used to make the build of the image on Dockerhub? And does giving the lbBaseURL still work for running locally - or do we have to set this some other way?

Many thanks.
